### ISSUE TITLE
Ability to define currency mask 

### ISSUE THREAD

**Issue by kefahB** [PeterStaev/nativescript-masked-text-field#23]
Hi,

I  try to find a solution for add a currency mask : 
```
5€
5,2$
10€
10.55€
```

Like you see the mask should be variable, i try to binding data to the mask but i got this error 
```xml
<mtf:MaskedTextField text="{{ price }}" hint="{{ L('price_ex') }}" id="priceInput" mask="{{ mask }}" keyboardType="phone" />
```
```sh
JS: Binding: Binding error while setting property price of [object Object]: TypeError: Cannot assign to read only property 'length' of string '0'
```

Do you think we can imagine to add a real regex into a mask like : `^[\d]+(\,|\.)?[\d]{0,2}$`

Thanks

**Comment by PeterStaev** [comment]
Hey @kefahB , the `mask` property is a string., so you cannot set it to a regex. Binding to a mask should work though, but from your sample code I do not know what mask are you setting. Please create a reproducible sample in the NativeScript playground that demonstrates the problem.

**Comment by kefahB** [comment]
Hey @PeterStaev, 

Her is playground with the problem [Test binding mask](https://play.nativescript.org/?template=play-tsc&id=GHDRXe&v=5)

**Comment by PeterStaev** [comment]
Well you can't have the mask depend on the price value... I'm not getting an error under iOS, but as soon as you enter something the widget is refreshed (since you change the mask) and basically you can't enter anything other than a single digit. So you have to think of another way to achieve what you want or use some other UI widget.
