### ISSUE TITLE
Getting 404 when trying to add plugin from ProPlugin

### ISSUE THREAD

**Issue by HazizKhan** [PeterStaev/nativescript-masked-text-field#47]
Hi,
i am trying to run given command on [https://npm.proplugins.org/-/web/detail/@proplugins/nativescript-masked-text-field](https://npm.proplugins.org/-/web/detail/@proplugins/nativescript-masked-text-field)
and i am getting 404.
can you please guide me if i'm doing anything wrong thank you so much :)

<img width="578" alt="Screenshot 2020-03-10 at 6 42 37 PM" src="https://user-images.githubusercontent.com/13147389/76318241-3abf0080-62ff-11ea-95ef-20ef9734230d.png">

**Comment by PeterStaev** [comment]
Hey @HazizKhan , the `@proplugins` scope is hosted in a private NPM server. In order to be able to use it you need to have an active subscription: https://proplugins.org/subscribe.html

Once you do, you can follow the instructions [here](https://accounts.nativescript.rocks/subscription/current) in order to set up npm.
